In [ ]:
## Array Creation Example
import numpy as np
np.array([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np. ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [7]:
np.full((2,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [9]:
## Sequence Creation Example
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
## np.eye = "identity matrix generator
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## NumPy is representing the numbers as floating-point values (float64 by default), not integers.
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [19]:
np.linspace(0, 20, 5, dtype=int)  # Generates 5 evenly spaced numbers between 0 and 1

array([ 0,  5, 10, 15, 20])

In [23]:
## Random Number Generation Example
np.random.seed(42)  # For reproducibility
np
random_array = np.random.rand(3, 3)  # Generates a 3x3 array of random floats between 0 and 1
random_integers = np.random.randint(1, 10, size=(2, 3))  # Generates a 2x3 array of random integers between 1 and 10
print("Random Array:\n", random_array)
print("Random Integers:\n", random_integers)

Random Array:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
Random Integers:
 [[8 3 6]
 [5 2 8]]
